apiVersion: v1
kind: Pod
metadata:
  name: manual-runner-dev-hello
  namespace: app
  labels:
    app: github-runner
    environment: dev
spec:
  containers:
  - name: runner
    image: summerwind/actions-runner:latest
    env:
    - name: GITHUB_TOKEN
      value: "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"
    - name: RUNNER_REPO
      value: "ninejuan/day2-product"
    - name: RUNNER_TOKEN
      value: "AS3KYFHLKQU3NDMDCUN3UZLIZJEDW"
    - name: RUNNER_NAME
      value: "dev-runner-1h2md-1dk3k"
    - name: RUNNER_LABELS
      value: "dev,self-hosted,Linux,X64"
    - name: RUNNER_WORKDIR
      value: "/runner/_work"
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    - name: DOCKER_BUILDKIT
      value: "1"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    volumeMounts:
    - name: work
      mountPath: /runner/_work
  - name: dind
    image: docker:24-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    args:
    - --host=tcp://0.0.0.0:2375
    - --host=unix:///var/run/docker.sock
    - --storage-driver=overlay2
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
  volumes:
  - name: work
    emptyDir: {}
  - name: dind-storage
    emptyDir: {}
  restartPolicy: Always
