name: Build and Update GAC App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/gac-app:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Clone gitops repo
        run: |
          git config --global user.name "Juan Lee"
          git config --global user.email "me@juany.kr"
          git clone https://x-access-token:${{ secrets.GAC_GITOPS_TOKEN }}@github.com/ninejuan/gac-gitops.git
          cd gac-gitops
          sed -i "s|image: .*|image: ${{ steps.login-ecr.outputs.registry }}/gac-app:${{ github.sha }}|" ./deploy/deployment.yaml
          git add ./deploy/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push origin main
