name: CI/CD Pipeline

on:
  push:
    paths:
      - 'index.html'
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: app-repo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read version file
      id: version
      run: |
        VERSION=$(cat version)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        
        # Push the Docker image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        echo "Image pushed: $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION"

    - name: Update deployment manifest
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        # Update the image in deploy.yaml
        sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION|g" manifest/deploy.yaml
        
        echo "Updated deploy.yaml with new image: $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION"

    - name: Commit and push changes
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add manifest/deploy.yaml
        git commit -m "Update image to $VERSION" || exit 0
        git push
