name: Chungnam-cicd-action

on:
  push:
    paths:
      - 'index.html'
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Read version file
        id: get_version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t app:latest .
          docker tag app:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/app-repo:${{ steps.get_version.outputs.version }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com/app-repo:${{ steps.get_version.outputs.version }}

      - name: update deploy.yaml with version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s|\(image: .*\):[[:alnum:]._-]\+|\1:$VERSION|" manifest/deploy.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest/deploy.yaml
          git commit -m "Update deploy.yaml with version ${{ steps.get_version.outputs.version }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
