apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: prod-runner
  namespace: app
spec:
  replicas: 2
  template:
    spec:
      repository: ninejuan/day2-product
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: DOCKER_BUILDKIT
          value: "1"
      labels:
        - prod
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      volumeMounts:
        - name: work
          mountPath: /runner/_work
      sidecarContainers:
        - name: dind
          image: docker:24-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args:
            - --host=tcp://0.0.0.0:2375
            - --host=unix:///var/run/docker.sock
            - --storage-driver=overlay2
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: work
          emptyDir: {}
        - name: dind-storage
          emptyDir: {}
