apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://ninejuan.github.io/day2-product/charts
      chart: app
      targetRevision: 1.0.2
      helm:
        valueFiles:
          - $values/values/dev.values.yaml
    - repoURL: https://github.com/ninejuan/day2-product.git
      targetRevision: dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
