apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://ninejuan.github.io/day2-product/charts
      chart: app
      targetRevision: 1.0.2
      helm:
        valueFiles:
          - $values/values/prod.values.yaml
    - repoURL: https://github.com/ninejuan/day2-product.git
      targetRevision: prod
      ref: values
  destination:
    server: https://8E161932BD5412D10F3A193E1C8AA3A6.gr7.eu-central-1.eks.amazonaws.com
    namespace: app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
