environment: prod
namespace: app

replicaCount: 3

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: prod-ingress
  className: "alb"
  albName: prod-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

rollouts:
  strategy:
    blueGreen:
      activeService: product-active
      previewService: product-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
